[package]
name = "reverseproxy"
version = "1.0.0"
edition = "2021"
description = "TCP Reverse Proxy written in Rust"
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
license = "MIT"
repository = "https://gitlab.com/p2kishimoto/reverseproxy"
readme = "README.md"

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.2.6", features = ["derive"]}
env_logger = "0.9.0"
futures = "0.3.21"
lazy_static = "1.4.0"
log = "0.4.14"
tokio = { version = "1.19.2", features = ["full"] }
tokio-socks = "0.5.1"
