[package]
name = "reverseproxy"
version = "0.1.0"
edition = "2021"
description = "TCP Reverse Proxy written in Rust"
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage = "https://github.com/yukibtc/reverseproxy"
repository = "https://github.com/yukibtc/reverseproxy.git"
license = "MIT"
readme = "README.md"

[features]
default = []
tor = ["libtor"]

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.2.6", features = ["derive"] }
env_logger = "0.9.0"
futures = "0.3.21"
libtor = { version = "47.8.0+0.4.7.x", features=["vendored-openssl"], optional = true }
log = "0.4.14"
rand = "0.8.5"
tokio = { version = "1.19.2", features = ["full"] }
tokio-socks = "0.5.1"

[profile.release]
lto = true
codegen-units = 1
