[workspace]
members = [
    "crates/reverseproxy",
    "crates/reverseproxy-config",
    "crates/reverseproxy-logger",
    "crates/reverseproxy-tcp",
    "crates/reverseproxy-tor",
    "crates/reverseproxy-util",
]