[package]
name = "reverseproxy"
version = "0.1.0"
edition = "2021"
description = "TCP Reverse Proxy written in Rust"
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage = "https://github.com/yukibtc/reverseproxy"
repository = "https://github.com/yukibtc/reverseproxy.git"
license = "MIT"
readme = "README.md"

[features]
default = []
tor = ["libtor"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
env_logger = "0.10"
futures = "0.3"
libtor = { version = "47.8.0+0.4.7.x", features=["vendored-openssl"], optional = true }
log = "0.4"
rand = "0.8"
tokio = { version = "1.32", features = ["macros", "net", "rt-multi-thread"] }
tokio-socks = "0.5"

[profile.release]
lto = true
codegen-units = 1
